ipv4_peers:
  - ipv4Address: "1.1.1.1"
    remoteAs: "200"
  - ipv4Address: "1.1.1.2"
    remoteAs: "400"
  - ipv4Address: "1.1.1.3"
    remoteAs: "200"
  - ipv4Address: "1.1.1.4"
    remoteAs: "400"
  - ipv4Address: "1.1.1.5"
    remoteAs: "200"
  - ipv4Address: "1.1.1.6"
    remoteAs: "400"
  - ipv4Address: "1.1.1.7"
    remoteAs: "200"
  - ipv4Address: "1.1.1.8"
    remoteAs: "400"
  - ipv4Address: "1.1.1.9"
    remoteAs: "200"
  - ipv4Address: "1.1.1.10"
    remoteAs: "400"
  - ipv4Address: "1.1.1.11"
    remoteAs: "200"
  - ipv4Address: "1.1.1.12"
    remoteAs: "400"
  - ipv4Address: "1.1.1.13"
    remoteAs: "200"
  - ipv4Address: "1.1.1.14"
    remoteAs: "400"
  - ipv4Address: "1.1.1.15"
    remoteAs: "200"
  - ipv4Address: "1.1.1.16"
    remoteAs: "400"
  - ipv4Address: "1.1.1.17"
    remoteAs: "200"
  - ipv4Address: "1.1.1.18"
    remoteAs: "400"
  - ipv4Address: "1.1.1.19"
    remoteAs: "200"
  - ipv4Address: "1.1.1.20"
    remoteAs: "400"
  - ipv4Address: "1.1.1.21"
    remoteAs: "200"
  - ipv4Address: "1.1.1.22"
    remoteAs: "400"
  - ipv4Address: "1.1.1.23"
    remoteAs: "200"
  - ipv4Address: "1.1.1.24"
    remoteAs: "400"
  - ipv4Address: "1.1.1.25"
    remoteAs: "200"
  - ipv4Address: "1.1.1.26"
    remoteAs: "400"
  - ipv4Address: "1.1.1.27"
    remoteAs: "200"
  - ipv4Address: "1.1.1.28"
    remoteAs: "400"
  - ipv4Address: "1.1.1.29"
    remoteAs: "200"
  - ipv4Address: "1.1.1.30"
    remoteAs: "400"
  - ipv4Address: "1.1.1.31"
    remoteAs: "200"
  - ipv4Address: "1.1.1.32"
    remoteAs: "400"
  - ipv4Address: "1.1.1.33"
    remoteAs: "200"
  - ipv4Address: "1.1.1.34"
    remoteAs: "400"
  - ipv4Address: "1.1.1.35"
    remoteAs: "200"
  - ipv4Address: "1.1.1.36"
    remoteAs: "400"
  - ipv4Address: "1.1.1.37"
    remoteAs: "200"
  - ipv4Address: "1.1.1.38"
    remoteAs: "400"
  - ipv4Address: "1.1.1.39"
    remoteAs: "200"
  - ipv4Address: "1.1.1.40"
    remoteAs: "400"
  - ipv4Address: "1.1.1.41"
    remoteAs: "200"
  - ipv4Address: "1.1.1.42"
    remoteAs: "400"
  - ipv4Address: "1.1.1.43"
    remoteAs: "200"
  - ipv4Address: "1.1.1.44"
    remoteAs: "400"
  - ipv4Address: "1.1.1.45"
    remoteAs: "200"
  - ipv4Address: "1.1.1.46"
    remoteAs: "400"
  - ipv4Address: "1.1.1.47"
    remoteAs: "200"
  - ipv4Address: "1.1.1.48"
    remoteAs: "400"
  - ipv4Address: "1.1.1.49"
    remoteAs: "200"
  - ipv4Address: "1.1.1.50"
    remoteAs: "400"
  - ipv4Address: "1.1.1.51"
    remoteAs: "200"
  - ipv4Address: "1.1.1.52"
    remoteAs: "400"
  - ipv4Address: "1.1.1.53"
    remoteAs: "200"
  - ipv4Address: "1.1.1.54"
    remoteAs: "400"
  - ipv4Address: "1.1.1.55"
    remoteAs: "200"
  - ipv4Address: "1.1.1.56"
    remoteAs: "400"
  - ipv4Address: "1.1.1.57"
    remoteAs: "200"
  - ipv4Address: "1.1.1.58"
    remoteAs: "400"
  - ipv4Address: "1.1.1.59"
    remoteAs: "200"
  - ipv4Address: "1.1.1.60"
    remoteAs: "400"
  - ipv4Address: "1.1.1.61"
    remoteAs: "200"
  - ipv4Address: "1.1.1.62"
    remoteAs: "400"
  - ipv4Address: "1.1.1.63"
    remoteAs: "200"
  - ipv4Address: "1.1.1.64"
    remoteAs: "400"
  - ipv4Address: "1.1.1.65"
    remoteAs: "200"
  - ipv4Address: "1.1.1.66"
    remoteAs: "400"
  - ipv4Address: "1.1.1.67"
    remoteAs: "200"
  - ipv4Address: "1.1.1.68"
    remoteAs: "400"
  - ipv4Address: "1.1.1.69"
    remoteAs: "200"
  - ipv4Address: "1.1.1.70"
    remoteAs: "400"
  - ipv4Address: "1.1.1.71"
    remoteAs: "200"
  - ipv4Address: "1.1.1.72"
    remoteAs: "400"
  - ipv4Address: "1.1.1.73"
    remoteAs: "200"
  - ipv4Address: "1.1.1.74"
    remoteAs: "400"
  - ipv4Address: "1.1.1.75"
    remoteAs: "200"
  - ipv4Address: "1.1.1.76"
    remoteAs: "400"
  - ipv4Address: "1.1.1.77"
    remoteAs: "200"
  - ipv4Address: "1.1.1.78"
    remoteAs: "400"
  - ipv4Address: "1.1.1.79"
    remoteAs: "200"
  - ipv4Address: "1.1.1.80"
    remoteAs: "400"
  - ipv4Address: "1.1.1.81"
    remoteAs: "200"
  - ipv4Address: "1.1.1.82"
    remoteAs: "400"
  - ipv4Address: "1.1.1.83"
    remoteAs: "200"
  - ipv4Address: "1.1.1.84"
    remoteAs: "400"
  - ipv4Address: "1.1.1.85"
    remoteAs: "200"
  - ipv4Address: "1.1.1.86"
    remoteAs: "400"
  - ipv4Address: "1.1.1.87"
    remoteAs: "200"
  - ipv4Address: "1.1.1.88"
    remoteAs: "400"
  - ipv4Address: "1.1.1.89"
    remoteAs: "200"
  - ipv4Address: "1.1.1.90"
    remoteAs: "400"
  - ipv4Address: "1.1.1.91"
    remoteAs: "200"
  - ipv4Address: "1.1.1.92"
    remoteAs: "400"
  - ipv4Address: "1.1.1.93"
    remoteAs: "200"
  - ipv4Address: "1.1.1.94"
    remoteAs: "400"
  - ipv4Address: "1.1.1.95"
    remoteAs: "200"
  - ipv4Address: "1.1.1.96"
    remoteAs: "400"
  - ipv4Address: "1.1.1.97"
    remoteAs: "200"
  - ipv4Address: "1.1.1.98"
    remoteAs: "400"
  - ipv4Address: "1.1.1.99"
    remoteAs: "200"
  - ipv4Address: "1.1.1.100"
    remoteAs: "400"

ipv6_peers:
  - ipv6Address: "1::1"
    remoteAs: "200"
  - ipv6Address: "1::2"
    remoteAs: "500"
  - ipv6Address: "1::3"
    remoteAs: "200"
  - ipv6Address: "1::4"
    remoteAs: "500"
  - ipv6Address: "1::5"
    remoteAs: "200"
  - ipv6Address: "1::6"
    remoteAs: "500"
  - ipv6Address: "1::7"
    remoteAs: "200"
  - ipv6Address: "1::8"
    remoteAs: "500"
  - ipv6Address: "1::9"
    remoteAs: "200"
  - ipv6Address: "1::10"
    remoteAs: "500"
  - ipv6Address: "1::11"
    remoteAs: "200"
  - ipv6Address: "1::12"
    remoteAs: "500"
  - ipv6Address: "1::13"
    remoteAs: "200"
  - ipv6Address: "1::14"
    remoteAs: "500"
  - ipv6Address: "1::15"
    remoteAs: "200"
  - ipv6Address: "1::16"
    remoteAs: "500"
  - ipv6Address: "1::17"
    remoteAs: "200"
  - ipv6Address: "1::18"
    remoteAs: "500"
  - ipv6Address: "1::19"
    remoteAs: "200"
  - ipv6Address: "1::20"
    remoteAs: "500"
  - ipv6Address: "1::21"
    remoteAs: "200"
  - ipv6Address: "1::22"
    remoteAs: "500"
  - ipv6Address: "1::23"
    remoteAs: "200"
  - ipv6Address: "1::24"
    remoteAs: "500"
  - ipv6Address: "1::25"
    remoteAs: "200"
  - ipv6Address: "1::26"
    remoteAs: "500"
  - ipv6Address: "1::27"
    remoteAs: "200"
  - ipv6Address: "1::28"
    remoteAs: "500"
  - ipv6Address: "1::29"
    remoteAs: "200"
  - ipv6Address: "1::30"
    remoteAs: "500"
  - ipv6Address: "1::31"
    remoteAs: "200"
  - ipv6Address: "1::32"
    remoteAs: "500"
  - ipv6Address: "1::33"
    remoteAs: "200"
  - ipv6Address: "1::34"
    remoteAs: "500"
  - ipv6Address: "1::35"
    remoteAs: "200"
  - ipv6Address: "1::36"
    remoteAs: "500"
  - ipv6Address: "1::37"
    remoteAs: "200"
  - ipv6Address: "1::38"
    remoteAs: "500"
  - ipv6Address: "1::39"
    remoteAs: "200"
  - ipv6Address: "1::40"
    remoteAs: "500"
  - ipv6Address: "1::41"
    remoteAs: "200"
  - ipv6Address: "1::42"
    remoteAs: "500"
  - ipv6Address: "1::43"
    remoteAs: "200"
  - ipv6Address: "1::44"
    remoteAs: "500"
  - ipv6Address: "1::45"
    remoteAs: "200"
  - ipv6Address: "1::46"
    remoteAs: "500"
  - ipv6Address: "1::47"
    remoteAs: "200"
  - ipv6Address: "1::48"
    remoteAs: "500"
  - ipv6Address: "1::49"
    remoteAs: "200"
  - ipv6Address: "1::50"
    remoteAs: "500"
  - ipv6Address: "1::51"
    remoteAs: "200"
  - ipv6Address: "1::52"
    remoteAs: "500"
  - ipv6Address: "1::53"
    remoteAs: "200"
  - ipv6Address: "1::54"
    remoteAs: "500"
  - ipv6Address: "1::55"
    remoteAs: "200"
  - ipv6Address: "1::56"
    remoteAs: "500"
  - ipv6Address: "1::57"
    remoteAs: "200"
  - ipv6Address: "1::58"
    remoteAs: "500"
  - ipv6Address: "1::59"
    remoteAs: "200"
  - ipv6Address: "1::60"
    remoteAs: "500"
  - ipv6Address: "1::61"
    remoteAs: "200"
  - ipv6Address: "1::62"
    remoteAs: "500"
  - ipv6Address: "1::63"
    remoteAs: "200"
  - ipv6Address: "1::64"
    remoteAs: "500"
  - ipv6Address: "1::65"
    remoteAs: "200"
  - ipv6Address: "1::66"
    remoteAs: "500"
  - ipv6Address: "1::67"
    remoteAs: "200"
  - ipv6Address: "1::68"
    remoteAs: "500"
  - ipv6Address: "1::69"
    remoteAs: "200"
  - ipv6Address: "1::70"
    remoteAs: "500"
  - ipv6Address: "1::71"
    remoteAs: "200"
  - ipv6Address: "1::72"
    remoteAs: "500"
  - ipv6Address: "1::73"
    remoteAs: "200"
  - ipv6Address: "1::74"
    remoteAs: "500"
  - ipv6Address: "1::75"
    remoteAs: "200"
  - ipv6Address: "1::76"
    remoteAs: "500"
  - ipv6Address: "1::77"
    remoteAs: "200"
  - ipv6Address: "1::78"
    remoteAs: "500"
  - ipv6Address: "1::79"
    remoteAs: "200"
  - ipv6Address: "1::80"
    remoteAs: "500"
  - ipv6Address: "1::81"
    remoteAs: "200"
  - ipv6Address: "1::82"
    remoteAs: "500"
  - ipv6Address: "1::83"
    remoteAs: "200"
  - ipv6Address: "1::84"
    remoteAs: "500"
  - ipv6Address: "1::85"
    remoteAs: "200"
  - ipv6Address: "1::86"
    remoteAs: "500"
  - ipv6Address: "1::87"
    remoteAs: "200"
  - ipv6Address: "1::88"
    remoteAs: "500"
  - ipv6Address: "1::89"
    remoteAs: "200"
  - ipv6Address: "1::90"
    remoteAs: "500"
  - ipv6Address: "1::91"
    remoteAs: "200"
  - ipv6Address: "1::92"
    remoteAs: "500"
  - ipv6Address: "1::93"
    remoteAs: "200"
  - ipv6Address: "1::94"
    remoteAs: "500"
  - ipv6Address: "1::95"
    remoteAs: "200"
  - ipv6Address: "1::96"
    remoteAs: "500"
  - ipv6Address: "1::97"
    remoteAs: "200"
  - ipv6Address: "1::98"
    remoteAs: "500"
  - ipv6Address: "1::99"
    remoteAs: "200"
  - ipv6Address: "1::100"
    remoteAs: "500"