ipv4_peers:
  - ipv4Address: "1.1.1.1"
    remoteAS: "200"
  - ipv4Address: "1.1.1.2"
    remoteAS: "400"
  - ipv4Address: "1.1.1.3"
    remoteAS: "200"
  - ipv4Address: "1.1.1.4"
    remoteAS: "400"
  - ipv4Address: "1.1.1.5"
    remoteAS: "200"
  - ipv4Address: "1.1.1.6"
    remoteAS: "400"
  - ipv4Address: "1.1.1.7"
    remoteAS: "200"
  - ipv4Address: "1.1.1.8"
    remoteAS: "400"
  - ipv4Address: "1.1.1.9"
    remoteAS: "200"
  - ipv4Address: "1.1.1.10"
    remoteAS: "400"
  - ipv4Address: "1.1.1.11"
    remoteAS: "200"
  - ipv4Address: "1.1.1.12"
    remoteAS: "400"
  - ipv4Address: "1.1.1.13"
    remoteAS: "200"
  - ipv4Address: "1.1.1.14"
    remoteAS: "400"
  - ipv4Address: "1.1.1.15"
    remoteAS: "200"
  - ipv4Address: "1.1.1.16"
    remoteAS: "400"
  - ipv4Address: "1.1.1.17"
    remoteAS: "200"
  - ipv4Address: "1.1.1.18"
    remoteAS: "400"
  - ipv4Address: "1.1.1.19"
    remoteAS: "200"
  - ipv4Address: "1.1.1.20"
    remoteAS: "400"
  - ipv4Address: "1.1.1.21"
    remoteAS: "200"
  - ipv4Address: "1.1.1.22"
    remoteAS: "400"
  - ipv4Address: "1.1.1.23"
    remoteAS: "200"
  - ipv4Address: "1.1.1.24"
    remoteAS: "400"
  - ipv4Address: "1.1.1.25"
    remoteAS: "200"
  - ipv4Address: "1.1.1.26"
    remoteAS: "400"
  - ipv4Address: "1.1.1.27"
    remoteAS: "200"
  - ipv4Address: "1.1.1.28"
    remoteAS: "400"
  - ipv4Address: "1.1.1.29"
    remoteAS: "200"
  - ipv4Address: "1.1.1.30"
    remoteAS: "400"
  - ipv4Address: "1.1.1.31"
    remoteAS: "200"
  - ipv4Address: "1.1.1.32"
    remoteAS: "400"
  - ipv4Address: "1.1.1.33"
    remoteAS: "200"
  - ipv4Address: "1.1.1.34"
    remoteAS: "400"
  - ipv4Address: "1.1.1.35"
    remoteAS: "200"
  - ipv4Address: "1.1.1.36"
    remoteAS: "400"
  - ipv4Address: "1.1.1.37"
    remoteAS: "200"
  - ipv4Address: "1.1.1.38"
    remoteAS: "400"
  - ipv4Address: "1.1.1.39"
    remoteAS: "200"
  - ipv4Address: "1.1.1.40"
    remoteAS: "400"
  - ipv4Address: "1.1.1.41"
    remoteAS: "200"
  - ipv4Address: "1.1.1.42"
    remoteAS: "400"
  - ipv4Address: "1.1.1.43"
    remoteAS: "200"
  - ipv4Address: "1.1.1.44"
    remoteAS: "400"
  - ipv4Address: "1.1.1.45"
    remoteAS: "200"
  - ipv4Address: "1.1.1.46"
    remoteAS: "400"
  - ipv4Address: "1.1.1.47"
    remoteAS: "200"
  - ipv4Address: "1.1.1.48"
    remoteAS: "400"
  - ipv4Address: "1.1.1.49"
    remoteAS: "200"
  - ipv4Address: "1.1.1.50"
    remoteAS: "400"
  - ipv4Address: "1.1.1.51"
    remoteAS: "200"
  - ipv4Address: "1.1.1.52"
    remoteAS: "400"
  - ipv4Address: "1.1.1.53"
    remoteAS: "200"
  - ipv4Address: "1.1.1.54"
    remoteAS: "400"
  - ipv4Address: "1.1.1.55"
    remoteAS: "200"
  - ipv4Address: "1.1.1.56"
    remoteAS: "400"
  - ipv4Address: "1.1.1.57"
    remoteAS: "200"
  - ipv4Address: "1.1.1.58"
    remoteAS: "400"
  - ipv4Address: "1.1.1.59"
    remoteAS: "200"
  - ipv4Address: "1.1.1.60"
    remoteAS: "400"
  - ipv4Address: "1.1.1.61"
    remoteAS: "200"
  - ipv4Address: "1.1.1.62"
    remoteAS: "400"
  - ipv4Address: "1.1.1.63"
    remoteAS: "200"
  - ipv4Address: "1.1.1.64"
    remoteAS: "400"
  - ipv4Address: "1.1.1.65"
    remoteAS: "200"
  - ipv4Address: "1.1.1.66"
    remoteAS: "400"
  - ipv4Address: "1.1.1.67"
    remoteAS: "200"
  - ipv4Address: "1.1.1.68"
    remoteAS: "400"
  - ipv4Address: "1.1.1.69"
    remoteAS: "200"
  - ipv4Address: "1.1.1.70"
    remoteAS: "400"
  - ipv4Address: "1.1.1.71"
    remoteAS: "200"
  - ipv4Address: "1.1.1.72"
    remoteAS: "400"
  - ipv4Address: "1.1.1.73"
    remoteAS: "200"
  - ipv4Address: "1.1.1.74"
    remoteAS: "400"
  - ipv4Address: "1.1.1.75"
    remoteAS: "200"
  - ipv4Address: "1.1.1.76"
    remoteAS: "400"
  - ipv4Address: "1.1.1.77"
    remoteAS: "200"
  - ipv4Address: "1.1.1.78"
    remoteAS: "400"
  - ipv4Address: "1.1.1.79"
    remoteAS: "200"
  - ipv4Address: "1.1.1.80"
    remoteAS: "400"
  - ipv4Address: "1.1.1.81"
    remoteAS: "200"
  - ipv4Address: "1.1.1.82"
    remoteAS: "400"
  - ipv4Address: "1.1.1.83"
    remoteAS: "200"
  - ipv4Address: "1.1.1.84"
    remoteAS: "400"
  - ipv4Address: "1.1.1.85"
    remoteAS: "200"
  - ipv4Address: "1.1.1.86"
    remoteAS: "400"
  - ipv4Address: "1.1.1.87"
    remoteAS: "200"
  - ipv4Address: "1.1.1.88"
    remoteAS: "400"
  - ipv4Address: "1.1.1.89"
    remoteAS: "200"
  - ipv4Address: "1.1.1.90"
    remoteAS: "400"
  - ipv4Address: "1.1.1.91"
    remoteAS: "200"
  - ipv4Address: "1.1.1.92"
    remoteAS: "400"
  - ipv4Address: "1.1.1.93"
    remoteAS: "200"
  - ipv4Address: "1.1.1.94"
    remoteAS: "400"
  - ipv4Address: "1.1.1.95"
    remoteAS: "200"
  - ipv4Address: "1.1.1.96"
    remoteAS: "400"
  - ipv4Address: "1.1.1.97"
    remoteAS: "200"
  - ipv4Address: "1.1.1.98"
    remoteAS: "400"
  - ipv4Address: "1.1.1.99"
    remoteAS: "200"
  - ipv4Address: "1.1.1.100"
    remoteAS: "400"

ipv6_peers:
  - ipv6Address: "1::1"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::2"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::3"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::4"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::5"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::6"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::7"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::8"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::9"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::10"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::11"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::12"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::13"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::14"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::15"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::16"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::17"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::18"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::19"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::20"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::21"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::22"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::23"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::24"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::25"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::26"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::27"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::28"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::29"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::30"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::31"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::32"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::33"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::34"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::35"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::36"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::37"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::38"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::39"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::40"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::41"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::42"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::43"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::44"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::45"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::46"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::47"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::48"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::49"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::50"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::51"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::52"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::53"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::54"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::55"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::56"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::57"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::58"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::59"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::60"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::61"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::62"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::63"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::64"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::65"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::66"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::67"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::68"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::69"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::70"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::71"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::72"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::73"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::74"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::75"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::76"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::77"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::78"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::79"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::80"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::81"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::82"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::83"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::84"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::85"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::86"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::87"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::88"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::89"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::90"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::91"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::92"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::93"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::94"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::95"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::96"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::97"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::98"
    ipv6Prefix: "64"
    remoteAS: "500"
  - ipv6Address: "1::99"
    ipv6Prefix: "64"
    remoteAS: "200"
  - ipv6Address: "1::100"
    ipv6Prefix: "64"
    remoteAS: "500"